### ISSUE TITLE
Test testEcho() in StarfixTest failing 

### ISSUE THREAD

**Issue by varad64** [starfixdev/starfix#104]
Hello, I'm new to the project and while running the `./mvnw compile quarkus:dev ` maven command the test **testEcho()** fails when the assertion seems to be satisfied with the same values. Does the assertion want the values to be different? I'm confused. Please find below the error log:

>2023-01-27 22:48:48,036 ERROR [io.qua.test] (Test runner thread) ==================== TEST REPORT #1 ====================
2023-01-27 22:48:48,041 ERROR [io.qua.test] (Test runner thread) Test StarfixTest#testEcho() failed
: org.opentest4j.AssertionFailedError: Echo Random String ==> expected: <This is some random String that I want to Echo

> but was: <This is some random String that I want to Echo

> >
>         at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
>         at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
>         at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
>         at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1152)
>         at dev.starfix.StarfixTest.testEcho(StarfixTest.java:43)

Thanks!

**Comment by varad64** [comment]
Update:

Tried it on a Linux machine using a VM and the test passes.

I believe the test fails on Windows as whitespace isn't being recognized. I tested the **testEcho()** method passing in trimmed versions of the strings to the assertEquals method and the test passes.

Please find the log below:

> All 4 tests are passing (0 skipped), 4 tests were run in 2953ms. Tests completed at 14:33:11.
> Press [space] to restart, [e] to edit command line args (currently ''), [r] to re-run, [o] Toggle test output, [h] for more options>
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD SUCCESS
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  50.032 s
> [INFO] Finished at: 2023-01-30T14:33:26+05:30
> [INFO] ------------------------------------------------------------------------

**Comment by varad64** [comment]
> Strange, this was working fine on gh-actions on a win64 machine. All the past builds are successful (Look at win64 build on https://github.com/starfixdev/starfix/actions).

Yeah, that is odd. Previous builds had no problems

**Comment by fahad-israr** [comment]
Rename Issue to Build Failing on Windows and add rest details in the description.

**Comment by Kshitiz-Mhto** [comment]
hello, @varad64. i have tested the testcases in windows server `2019` and `2022` / `latest` using github action, it is working fine.
are u using default jdk or the one provided by GraalVM ?

**Comment by fahad-israr** [comment]
@Kshitiz-Mhto ref this : https://github.com/starfixdev/starfix/actions/runs/4097448503/jobs/7065829580

**Comment by Kshitiz-Mhto** [comment]
@fahad-israr  i have fixed the testEcho() test failing on windows, further i am working in command `mvn package -Dnative` for building native-image

**Comment by fahad-israr** [comment]
Great @Kshitiz-Mhto .
Link your PR too with the issue.

**Comment by fahad-israr** [comment]
Logging a strange event : Build did not fail when i created a PR https://github.com/starfixdev/starfix/pull/122. gh-actions workflow logs here: https://github.com/starfixdev/starfix/actions/runs/4239906148/jobs/7368393153
