### ISSUE TITLE
Unable to execute config command on the generated Native Binary after merging jbangify PR .

### ISSUE THREAD

**Issue by fahad-israr** [starfixdev/starfix#54]
Unable to execute config command on the generated Native Binary after merging the jbagify [PR] (https://github.com/starfixdev/starfix/pull/50)  from @maxandersen  .
On Screen Logs :
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class dev.starfix.Starfix$Config and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1277)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4407)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3602)
	at dev.starfix.Starfix.editConfig(Starfix.java:196)
	at dev.starfix.Starfix.config(Starfix.java:39)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1952)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:39)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:113)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)

```

**Comment by maxandersen** [comment]
Quarkus needs a hint to know the class is relevant for jackson to do reflection on.

issue and solution found at https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection

**Comment by fahad-israr** [comment]
Thanks @maxandersen 
I'll have a look at it .

**Comment by fahad-israr** [comment]
Simple adding the annotation `@RegisterForReflection` didn't work for me, probably I am missing something else. 
It'd be helpful If I can see any existing code. @maxandersen  If possible, can you please share any  git repository  .

**Comment by maxandersen** [comment]
I'll look. For now just run as jar directly or use jbang.
