### ISSUE TITLE
starfix fails on urls with github line info or any other #argument

### ISSUE THREAD

**Issue by maxandersen** [starfixdev/starfix#61]
`starfix https://github.com/hexsum/Mojo-Webqq/blob/master/script/check_dependencies.pl#L17`

fails with

```
 starfix https://github.com/hexsum/Mojo-Webqq/blob/master/script/check_dependencies.pl#L17
java.lang.IllegalArgumentException: Not a valid URI for git repository
	at dev.starfix.Starfix.cloneCmd(Starfix.java:53)
	at dev.starfix.Starfix.run(Starfix.java:131)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
```

shuold not fail optimally open on that line if possible.

**Comment by maxandersen** [comment]
another issue - spaces https://github.com/maxandersen/reallyevil/blob/main/here%20is%20a%20space.txt
